AuctionZ/Models/LotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ApplicationCore.DTO;
using ApplicationCore.Entities;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ValidationContext = System.ComponentModel.DataAnnotations.ValidationContext;

namespace AuctionZ.Models
{
    public class LotViewModel : IValidatableObject
    {
        [ScaffoldColumn(false)]
        public int LotId { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "The field can not be empty!")]
        [StringLength(100)]
        public string Name { get; set; }

        [Display(Name = "Starting price")]
        [DataType(DataType.Currency)]
        [Range(typeof(decimal), "1", "10000", ErrorMessage = "Invalid price")]
        [Required(ErrorMessage = "The field must be filled")]
        public decimal Price { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Expiration time")]
        [Required(ErrorMessage = "The field must be filled")]
        public DateTime ExpirationTime { get; set; } = DateTime.Now.AddDays(7);

        [Display(Name = "Category")]
        [Required(ErrorMessage = "The category is required!")]
        public int CategoryId { get; set; }
        
        public string Description { get; set; }
        public int UserId { get; set; }
        public UserDto User { get; set; }

        [Display(Name ="Image")]
        public string ImageUrl { get; set; }

        //Optional
        public IEnumerable<BidViewModel> Bids { get; set; }
        public IEnumerable<SelectListItem> Categories { get; set; }
        [Display(Name = "Image")]
        public IFormFile ImageFile { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> results = new List<ValidationResult>();
            if (ExpirationTime < DateTime.Now)
            {
                results.Add(new ValidationResult($"Expiration date must be greater than {DateTime.Now}", new[] { "ExpirationTime" }));
            }
            return results;
        }
    }
}

AuctionZ/Models/LotsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using AuctionZ.Models.Utils;

namespace AuctionZ.Models
{
    public class LotsViewModel
    {
        public IEnumerable<LotViewModel> Lots { get; set; }
        public PageViewModel Pagination { get; set; }
        public FilterViewModel Filter { get; set; }
    }
}

AuctionZ/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Transactions;
using ApplicationCore;
using ApplicationCore.DTO;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using AuctionZ.Models;
using AuctionZ.Models.MappingProfiles;
using AuctionZ.Models.Utils;
using AutoMapper;
using Infrastructure.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using static AuctionZ.Utils.Utils;

namespace AuctionZ.Controllers
{
    public class AuctionController : BaseController
    {
        private readonly ILotsService _lotsService;
        private readonly IBidsService _bidsService;
        private readonly IUserServices _usersServices;
        private readonly ILogger<AuctionController> _logger;
        private readonly IHubContext<LotHub> _hubcontext;

        public AuctionController(ILogger<AuctionController> logger,
            ILotsService lotsService, IBidsService bidsService,
            IUserServices userServices, IHubContext<LotHub> hubcontext)
        {
            _lotsService = lotsService;
            _bidsService = bidsService;
            _usersServices = userServices;
            _hubcontext = hubcontext;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(int? category, string title, int page=1)
        {
           int pageSize = 4;
           var criteria = new LotsFilterCriteria()
                {Page = page, Category = category, Title = title, PageSize = pageSize, Active = true};
           var lots = _lotsService.GetAllLots(criteria).ToVm();
           var model = new LotsViewModel()
           {
               Lots = lots,
               Pagination = new PageViewModel(_lotsService.GetLotsCount(criteria), page, pageSize),
               Filter = new FilterViewModel(GetCategories(), title, category)
           };       
           return View(model);
        }

        public IActionResult Details(int lotId)
        {
            var lot_vm = _lotsService.GetItem(lotId).ToVm();
            lot_vm.Bids = _bidsService.GetAllBidsForLotWithUsers(lot_vm.LotId)
                .OrderByDescending(x => x.DateOfBid).ToVm();
            return View(lot_vm);
        }

        [HttpGet]
        [Authorize(Roles="admin,user")]
        public IActionResult EditLot(int lotId)
        {
            var lot = _lotsService.GetItem(lotId);
            if (lot == null || (lot.UserId != UserId))
                return StatusCode(404);
            var lotVm = lot.ToVm();
            lotVm.Categories= GetCategoriesSelectListItems(lot.CategoryId);
            return View(lotVm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin,user")]
        public IActionResult EditLot(int lotId, LotViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.ImageUrl = SaveImage(vm.ImageFile,
                    HttpContext.RequestServices.GetRequiredService<IHostingEnvironment>());
                var lot = vm.ToDto();
                _lotsService.Update(lot);
                return RedirectToAction(nameof(Details), new { lotId = lot.LotId}); 
            }
            // Re-fetch data
            vm.Categories = GetCategoriesSelectListItems(vm.CategoryId);
            return View(vm);
        }

        [HttpGet]
        public IActionResult DeleteLot(int lotId)
        {
            var lotVm = _lotsService.GetItem(lotId).ToVm();
            return View(lotVm);
        }

        [HttpPost]
        [ActionName("DeleteLot")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteLotConfirmed(int lotId)
        {
            _lotsService.RemoveItem(lotId);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> MakeBid([FromBody]BidDto bid)
        {
            var lot = _lotsService.GetItem(bid.LotId);
            if (lot == null)
                return BadRequest();
            var user = _usersServices.GetItem(UserId);
            if (lot.Price >= bid.Price)
                ModelState.AddModelError(nameof(bid.Price), "Bid must be greater than value price");
            if (user.Money < bid.Price)
                ModelState.AddModelError(nameof(bid.Price), "Not enough funds");
            if (ModelState.IsValid)
            {
                _usersServices.MakeBid(lot.LotId, UserId, bid.Price);
                var lastbid = _bidsService.GetLastBidForLot(bid.LotId);
                var row_info = string.Format("<tr><td>{0}</td><td>{1}</td><td>{2}</td></tr", lastbid.User.UserName,
                        lastbid.Price.ToString("C"), lastbid.DateOfBid.ToString("f"));
                await _hubcontext.Clients.All.SendAsync("BidMade",
                  lot.LotId, row_info, lastbid.Price.ToString("C"));
                return Ok();
                //return new ObjectResult(new {row = row_info});
            }
            return new BadRequestObjectResult(ModelState);
        }


        //
//        [HttpPost("{id}")]
//        [Authorize]
//        public IActioResult MakeBid(int lotId, [FromBody]decimal bidValue)
//        {
//            return 
//        }

        private IEnumerable<CategoryDto> GetCategories()
        {
            var categoryService = HttpContext.RequestServices.GetRequiredService<ICategoryService>();
            return categoryService.GetItems();
        }

        private IEnumerable<SelectListItem> GetCategoriesSelectListItems(int? selectedId=0)
        {
            return GetCategories()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.CategoryId.ToString(),
                    Selected = selectedId == c.CategoryId
                });
        }

    }
}

AuctionZ/Controllers/ProfileController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using ApplicationCore;
using ApplicationCore.DTO;
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using AuctionZ.Models;
using AuctionZ.Models.MappingProfiles;
using AuctionZ.Models.Utils;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using static AuctionZ.Utils.Utils;
using AuctionZ.Models.MappingProfiles;

namespace AuctionZ.Controllers
{

    [Authorize]
    public class ProfileController : BaseController
    {

        private readonly ILotsService _lotsService;
        private readonly IBidsService _bidsService;
        private readonly IUserServices _usersServices;
        private readonly ILogger<ProfileController> _logger;

        public ProfileController(ILogger<ProfileController> logger,
            ILotsService lotsService, 
            IBidsService bidsService,
            IUserServices usersService, ICategoryRepository categoryRepository)
        {
            _lotsService = lotsService;
            _bidsService = bidsService;
            _usersServices = usersService;
        }

        public IActionResult Index() => RedirectToAction(nameof(Info));

        [HttpGet]
        public IActionResult Info()
        {
            var profile = _usersServices.GetItem(UserId).ToVm();
            return View(profile);
        }

        [HttpPost]
        public IActionResult Info(ProfileViewModel vm)
        {
            _usersServices.Update(vm.ToDto());
            return RedirectToAction(nameof(Info));
        }

        public IActionResult Lots(int? category, string title, int page = 1, bool? active=null)
        {
            int pageSize = 4;
            var criteria = new LotsFilterCriteria()
                { Page = page, Category = category, Title = title, PageSize = pageSize, Active = active, UserId = UserId};
            var lots = _lotsService.GetAllLots(criteria).ToVm();
            var model = new LotsViewModel()
            {
                Lots = lots,
                Pagination = new PageViewModel(_lotsService.GetLotsCount(criteria), page, pageSize),
                Filter = new FilterViewModel(GetCategories(), title, category, active)
            };
            return View(model);
        }

        public IActionResult Bids()
        {
            var lots = _bidsService.GetAllBidsForUser(UserId).ToVm();
            return View(lots);
        }


        public IActionResult Purchases()
        {
            var lots = _lotsService.GetUserPurchases(UserId).ToVm();
            return View(lots);
        }

        [HttpGet]
        public IActionResult CreateLot()
        {
            var vm = new LotViewModel {UserId = UserId, Categories = GetCategoriesSelectListItems()};
            return View(vm);
        }

        [HttpPost]
        public IActionResult CreateLot(LotViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.ImageUrl = SaveImage(vm.ImageFile,
                                  HttpContext.RequestServices.GetRequiredService<IHostingEnvironment>());
                var lot = _lotsService.AddItem(vm.ToDto());
                return RedirectToAction(nameof(Lots), lot.LotId);
            }

            vm.Categories = GetCategoriesSelectListItems(vm.CategoryId);
            return View(vm);
        }

        private IEnumerable<CategoryDto> GetCategories()
        {
            var categoryService = HttpContext.RequestServices.GetRequiredService<ICategoryService>();
            return categoryService.GetItems();
        }

        private IEnumerable<SelectListItem> GetCategoriesSelectListItems(int? selectedId = 0)
        {
            return GetCategories()
                .Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.CategoryId.ToString(),
                    Selected = selectedId == c.CategoryId
                });
        }


    }
}

AuctionZ/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using ApplicationCore.Entities
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuctionZ</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container form-inline">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Auction" asp-action="Index" class="navbar-brand">AuctionZ</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Auction" asp-action="Index">Auction</a></li>
                        <li><a asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>
                    <li><a asp-area="" asp-controller="Profile" asp-action="Index">Profile</a></li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
        <script src="~/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
        <script src="~/lib/signalr/dist/browser/signalr.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.12.0/moment.js"></script>
        <script src="~/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    </environment>
    <div style="margin-top: 2%" class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AuctionZ</p>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>

AuctionZ/Views/Shared/_Lots.cshtml
@using ApplicationCore.Entities
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.AspNetCore.Routing
@using Microsoft.Extensions.Localization
@inject IViewLocalizer Localizer
@model IEnumerable<LotViewModel>
@{
    var controller = Context.GetRouteData().Values["controller"].ToString();
    var expanded = controller == "Admin";

}
<table class="table table-bordered" style="margin-top: 2%">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpirationTime)
            </th>
            @if (expanded) { <th>Owner</th>}
            <th>@Localizer["Actions"]</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpirationTime)
                </td>
                @if (expanded) { <td>
                                     @Html.DisplayFor(modelItem => item.User.UserName)
                                 </td>

                }
                <td>

                    <a style="float: left; margin-right: 2%"
                       asp-controller="Auction"
                       asp-action="Details"
                       asp-route-lotId="@item.LotId"
                       class="btn btn-info">
                        Details
                    </a>
                    <a style="float: left; margin-right: 2% "
                       asp-controller="Auction" asp-action="EditLot"
                       asp-route-lotid="@item.LotId"
                       class="btn btn-success">
                        EditLot
                    </a>
                    <form class="form-inline" style="float: left; margin-right: 2% " method="post" asp-controller="Auction" asp-action="DeleteLot"
                          asp-route-lotId="@item.LotId"
                          asp-antiforgery="true">
                        <button type="submit" onclick="if (!confirm('Are you sure want to delete lot?')) return false;"
                               class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>